### ISSUE TITLE
Invoke-IcingaCheckService without arguments bug - fix included

### ISSUE THREAD

**Issue by FxMH** [Icinga/icinga-powershell-plugins#121] opened 2021-01-08 09:44 UTC
Hi Christian,

the Invoke-IcingaCheckService command without arguments is expected to check all services on autostart that terminated with a return code other than 0. This doesn't work in your implementation at the moment.

Steps to reproduce:
- Get Process ID of Spooler service [eg. from Taskmanager] - in my case 6296
- from a powershell run `taskkill /pid 6296 /f`
- the Spooler service is stopped with an error-code other than 0
- switch to Icinga shell in Powershell -> `icinga`
- run `Invoke-IcingaCheckService`

Result:
`icinga> Invoke-IcingaCheckService
Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins\Invoke-IcingaCheckService.psm1:111 char:13
+             $ServicesPackage.AddCheck(
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

[OK] Check package "Services"
| 'pending_paused_services'=0;; 'running_services'=59;; 'pending_continued_services'=0;; 'stopped_services'=6;; 'pending_started_services'=0;; 'service_count'=65;; 'pending_stopp
ed_services'=0;; 'paused_services'=0;;
0`

-> apply my fix (attached at the end)

`icinga> Invoke-IcingaCheckService
[CRITICAL] Check package "Services" - [CRITICAL] Service "Print Spooler (Spooler)"
\_ [CRITICAL] Service "Print Spooler (Spooler)": Value "Stopped" is not matching threshold "Running"
| 'pending_paused_services'=0;; 'running_services'=58;; 'pending_continued_services'=0;; 'stopped_services'=6;; 'pending
_started_services'=0;; 'service_count'=64;; 'pending_stopped_services'=0;; 'paused_services'=0;;
2`

Best regards,
Felix

Fix: Replace your lines 83 to 114 with this code
`    if ($Service.Count -eq 0) {
        $AutoServices = Get-IcingaServices -Exclude $Exclude;
        foreach ($autoservice in $AutoServices.Keys) {

            # Skip services which are not defined to run automatically
            if ($AutoServices.$autoservice.configuration.StartType.Raw -ne $ProviderEnums.ServiceStartupType.Automatic) {
                continue;
            }

            $ServiceSummary = Add-IcingaServiceSummary -ServiceStatus $AutoServices.$autoservice.configuration.Status.Raw -ServiceData $ServiceSummary;

            # Check if the service is running
            if ($AutoServices.$autoservice.configuration.Status.Raw -eq $ProviderEnums.ServiceStatus.Running) {
                $ServicesPackage.AddCheck(
                    (New-IcingaWindowsServiceCheckObject -Status 'Running' -Service $AutoServices.$autoservice -NoPerfData)
                );
                continue;
            }

            # Service is not running bug the ExitCode is 0 -> this is fine and should not raise a critical
            if ($AutoServices.$autoservice.configuration.ExitCode -eq 0) {
                $ServicesPackage.AddCheck(
                    (New-IcingaWindowsServiceCheckObject -Status 'Stopped' -Service $AutoServices.$autoservice -NoPerfData)
                );
                continue;
            }

            # Services which should be running, but are not
            $ServicesPackage.AddCheck(
                (New-IcingaWindowsServiceCheckObject -Status 'Running' -Service $AutoServices.$autoservice -NoPerfData)
            );
        }`

**Comment by LordHepipud** [comment] 2021-01-21 11:16
Thank you for the input and report! The issue is fixed with the linked PR.

**Closed** 2021-01-21 11:15 UTC
Labels: bug
