### ISSUE TITLE
Invoke-IcingaCheckEventlog - unit "d" doesn't work correctly

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-plugins#145] opened 2021-03-15 10:09 UTC
While testing the check "Invoke-IcingaCheckEventlog" from the new framework (1.4.1)/plugins (1.4.0) version we recognize that the unit "d" ist not working correctly with the parameters "-After" and "-Before"  - e.g. "1d". In contrast, the value "24h" works fine. 

On our test server we find these messages in the eventlog - good to test the check:
![image](https://user-images.githubusercontent.com/38723488/111136380-fb646900-857d-11eb-963e-7a0f1e1543a7.png)

For us it looks like that the unit "d" is misinterpreted. Because if we set the parameter "-Before 1d" the result is similar "-After 24h". And the parameter "-After 1d" delivers nothing. 
![image](https://user-images.githubusercontent.com/38723488/111137071-ad039a00-857e-11eb-924a-d40be2c04509.png)

As you can see, with "-Before 1d" the output is completly wrong. Because if I run the command now (15.3.)

**Comment by LordHepipud** [comment] 2021-04-23 11:51
Could you please try this again with the latest version of the EventLog plugin, provided by the current master?
There was a fixed I merged today for a different filtering issue. I assume this one is fixed as well in addition, because I can't reproduce it with this one.

**Comment by LordHepipud** [comment] 2021-05-28 18:43
Is this still an issue with the new plugin?

**Closed** 2021-05-28 18:46 UTC
Labels: bug

**Comment by stevie-sy** [comment] 2021-05-31 10:50
Sorry for the late response. I tested it with the master from today. Same result:
![image](https://user-images.githubusercontent.com/38723488/120182418-a6e09980-c20e-11eb-8f68-784f7b2bcdef.png)
