### ISSUE TITLE
Invoke-IcingaCheckDiskHealth Plugin output "MethodInvocationException"

### ISSUE THREAD

**Issue by aheinhold** [Icinga/icinga-powershell-plugins#53] opened 2020-08-27 07:18 UTC
Hello again,

after granting the [required permissions](https://github.com/Icinga/icinga-powershell-framework/issues/111#issuecomment-680829333), the "Invoke-IcingaCheckDiskHealth" works but there is the following plugin output:
```
Plugin-Ausgabe
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[WARNING] Check package "Physical Disk Package" - [WARNING] 1 Is Offline, 1 Is ReadOnly, 2 Is Offline, 3 Is Offline 
\_ [WARNING] Check package "Disk #1"
   \_ [WARNING] 1 Is Offline: Value "True" is matching threshold "True"
   \_ [WARNING] 1 Is ReadOnly: Value "True" is matching threshold "True"
\_ [WARNING] Check package "Disk #2"
   \_ [WARNING] 2 Is Offline: Value "True" is matching threshold "True"
\_ [WARNING] Check package "Disk #3"
   \_ [WARNING] 3 Is Offline: Value "True" is matching threshold "True"
```

I used the version from [this branch](https://github.com/Icinga/icinga-powershell-plugins/tree/feature/implement-check-physicaldisk-35).

**Comment by Yonas-net** [comment] 2020-08-27 08:11
Hii @aheinhold , thanks for your report. If you update your branch, the error message should no longer appear. 

Best,
YH

**Comment by Yonas-net** [comment] 2020-08-27 08:17
Hii @aheinhold , thanks for your report. If you update your branch, the error message should no longer appear. .

Best,
YH

**Comment by aheinhold** [comment] 2020-08-27 09:23
Hi @Yonas-net  ,

the error message still appears... :-(
```
Plugin-Ausgabe
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[OK] Check package "Physical Disk Package" (Match All)
\_ [OK] Check package "Disk #_Total" (Match All)
   \_ [OK] _Total avg. disk sec/read: 0.002382s
   \_ [OK] _Total avg. disk sec/transfer: 0.003282s
   \_ [OK] _Total avg. disk sec/write: 0.003882s
   \_ [OK] _Total current disk queue length: 0
   \_ [OK] _Total disk read bytes/sec: 12001.070312B
   \_ [OK] _Total disk reads/sec: 3.012432
   \_ [OK] _Total disk write bytes/sec: 110412.203125B
   \_ [OK] _Total disk writes/sec: 4.557074
\_ [OK] Check package "Disk #0" (Match All)
   \_ [OK] C: avg. disk sec/read: 0.002382s
   \_ [OK] C: avg. disk sec/transfer: 0.003282s
   \_ [OK] C: avg. disk sec/write: 0.003882s
   \_ [OK] C: current disk queue length: 0
   \_ [OK] C: disk read bytes/sec: 7248.899902B
   \_ [OK] C: disk reads/sec: 3.012602
   \_ [OK] C: disk write bytes/sec: 110437.523438B
   \_ [OK] C: disk writes/sec: 4.579093
   \_ [OK] C: Is Offline: False
   \_ [OK] C: Is ReadOnly: False
   \_ [OK] C: Status: OK
```

**Comment by Yonas-net** [comment] 2020-08-27 10:01
Try it again now and if it is still not fixed, please run the following commands manually on the server where the checks are performed and then post the output here as a comment.
```
Use-icinga;
icinga { Invoke-IcingaCheckDiskHealth -Verbosity 2  }
```

**Comment by aheinhold** [comment] 2020-08-27 11:57
Manual execution on the target system:

**Command-Output: Invoke-IcingaCheckDiskHealth**
```
[OK] Check package "Physical Disk Package"
| 'c_avg_disk_secwrite'=0.002921s;; 'c_disk_read_bytessec'=82681.546875B;; 'c_current_disk_queue_length'=0;; 'c_avg_disk_secread'=0.00144s;; 'c_disk_write_bytessec'=12244
2.195312B;; 'c_disk_writessec'=3.956389;; 'c_avg_disk_sectransfer'=0.002043s;; 'c_disk_readssec'=5.764386;; '_total_disk_readssec'=5.764386;; '_total_avg_disk_sectransfer
'=0.002043s;; '_total_disk_read_bytessec'=82681.554688B;; '_total_disk_write_bytessec'=122442.203125B;; '_total_avg_disk_secread'=0.00144s;; '_total_disk_writessec'=3.956
4;; '_total_current_disk_queue_length'=0;; '_total_avg_disk_secwrite'=0.002921s;; 
0
```

**Command-Output: icinga { Invoke-IcingaCheckDiskHealth -Verbosity 2 }**
```
[OK] Check package "Physical Disk Package" (Match All)
\_ [OK] Check package "Disk #_Total" (Match All)
   \_ [OK] _Total avg. disk sec/read: 0s
   \_ [OK] _Total avg. disk sec/transfer: 0s
   \_ [OK] _Total avg. disk sec/write: 0s
   \_ [OK] _Total current disk queue length: 0
   \_ [OK] _Total disk read bytes/sec: 0B
   \_ [OK] _Total disk reads/sec: 0
   \_ [OK] _Total disk write bytes/sec: 0B
   \_ [OK] _Total disk writes/sec: 0
\_ [OK] Check package "Disk #0" (Match All)
   \_ [OK] C: avg. disk sec/read: 0s
   \_ [OK] C: avg. disk sec/transfer: 0s
   \_ [OK] C: avg. disk sec/write: 0s
   \_ [OK] C: current disk queue length: 0
   \_ [OK] C: disk read bytes/sec: 198159.171875B
   \_ [OK] C: disk reads/sec: 0
   \_ [OK] C: disk write bytes/sec: 0B
   \_ [OK] C: disk writes/sec: 0
[OK] Check package "Physical Disk Package" (Match All)


\_ [OK] Check package "Disk #_Total" (Match All)


   \_ [OK] _Total avg. disk sec/read: 0s


   \_ [OK] _Total avg. disk sec/transfer: 0s


   \_ [OK] _Total avg. disk sec/write: 0s


   \_ [OK] _Total current disk queue length: 0


   \_ [OK] _Total disk read bytes/sec: 0B


   \_ [OK] _Total disk reads/sec: 0


   \_ [OK] _Total disk write bytes/sec: 0B


   \_ [OK] _Total disk writes/sec: 0


\_ [OK] Check package "Disk #0" (Match All)


   \_ [OK] C: avg. disk sec/read: 0s


   \_ [OK] C: avg. disk sec/transfer: 0s


   \_ [OK] C: avg. disk sec/write: 0s


   \_ [OK] C: current disk queue length: 0


   \_ [OK] C: disk read bytes/sec: 198159.171875B


   \_ [OK] C: disk reads/sec: 0


   \_ [OK] C: disk write bytes/sec: 0B


   \_ [OK] C: disk writes/sec: 0


   \_ [OK] C: Is Offline: False


   \_ [OK] C: Is ReadOnly: False


   \_ [OK] C: Operational Status: OK


   \_ [OK] C: Status: OK


| 'c_avg_disk_secwrite'=0s;; 'c_disk_read_bytessec'=198159.171875B;; 'c_current_disk_queue_length'=0;; 'c_avg_disk_secread'=0s;; 'c_disk_write_bytessec'=0B;; 'c_disk_writ
essec'=0;; 'c_avg_disk_sectransfer'=0s;; 'c_disk_readssec'=0;; '_total_disk_readssec'=0;; '_total_avg_disk_sectransfer'=0s;; '_total_disk_read_bytessec'=0B;; '_total_disk
_write_bytessec'=0B;; '_total_avg_disk_secread'=0s;; '_total_disk_writessec'=0;; '_total_current_disk_queue_length'=0;; '_total_avg_disk_secwrite'=0s;; 


0
   \_ [OK] C: Is Offline: False
   \_ [OK] C: Is ReadOnly: False
   \_ [OK] C: Operational Status: OK
   \_ [OK] C: Status: OK
| 'c_avg_disk_secwrite'=0s;; 'c_disk_read_bytessec'=198159.171875B;; 'c_current_disk_queue_length'=0;; 'c_avg_disk_secread'=0s;; 'c_disk_write_bytessec'=0B;; 'c_disk_writ
essec'=0;; 'c_avg_disk_sectransfer'=0s;; 'c_disk_readssec'=0;; '_total_disk_readssec'=0;; '_total_avg_disk_sectransfer'=0s;; '_total_disk_read_bytessec'=0B;; '_total_disk
_write_bytessec'=0B;; '_total_avg_disk_secread'=0s;; '_total_disk_writessec'=0;; '_total_current_disk_queue_length'=0;; '_total_avg_disk_secwrite'=0s;; 

PS C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins> 
```

The error still appears in the Icinga-Gui and on satellite commandline. We use our own "check_by_pwsh".

**Comment by Yonas-net** [comment] 2020-08-27 15:41
Is the user with which the plugin was executed locally identical to the check_by_pwsh user? If not, try to run it locally with the same user and see if the error still occurs. And if you have the possibility to test it from a Linux System with check_by_pwsh and post the output right here, that would be great. The current info is unfortunately not enough to reproduce the same error in our system. And please update the branch first.

**Comment by aheinhold** [comment] 2020-09-02 11:49
The **commandline output** on the Windows-Server looks good if i use our "Icinga-Remote-User":
```
PS C:\Program Files\WindowsPowerShell\Modules> use-Icinga; Invoke-IcingaCheckDiskHealth
[OK] Check package "Physical Disk Package"
| 'c_avg_disk_secwrite'=0.006120s;; 'c_disk_read_bytessec'=8889869B;; 'c_current_disk_queue_length'=0;; 'c_avg_disk_secread'=0.003971s;; 'c_disk_write_bytessec'=286973.6B;; 'c_disk_writessec'=8.204155;; 'c_avg_disk_sectransfer'=0.004691s;; 'c_disk_readssec'=83.02791;; '_total_disk_readssec'=83.07169;; '_total_avg_disk_sectransfer'=0.004691s;; '_total_disk_read_bytessec'=8879079B;; '_total_disk_write_bytessec'=287215.7B;; '_total_avg_disk_secread'=0.003995s;; '_total_disk_writessec'=8.199403;; '_total_current_disk_queue_length'=0;; '_total_avg_disk_secwrite'=0.006120s;;
0
```

**The Icinga plugin output:**
```
Plugin-Ausgabe
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[OK] Check package "Physical Disk Package" (Match All)
\_ [OK] Check package "Disk #_Total" (Match All)
   \_ [OK] _Total avg. disk sec/read: 0.001169s
   \_ [OK] _Total avg. disk sec/transfer: 0.001169s
   \_ [OK] _Total avg. disk sec/write: 0s
   \_ [OK] _Total current disk queue length: 0
   \_ [OK] _Total disk read bytes/sec: 103574B
   \_ [OK] _Total disk reads/sec: 3.402522
   \_ [OK] _Total disk write bytes/sec: 0B
   \_ [OK] _Total disk writes/sec: 0
\_ [OK] Check package "Disk #0" (Match All)
   \_ [OK] C: avg. disk sec/read: 0.001169s
   \_ [OK] C: avg. disk sec/transfer: 0.001169s
   \_ [OK] C: avg. disk sec/write: 0s
   \_ [OK] C: current disk queue length: 0
   \_ [OK] C: disk read bytes/sec: 68755.04B
   \_ [OK] C: disk reads/sec: 3.405134
   \_ [OK] C: disk write bytes/sec: 0B
   \_ [OK] C: disk writes/sec: 0
   \_ [OK] C: Is Offline: False
   \_ [OK] C: Is ReadOnly: False
   \_ [OK] C: Status: OK
```

**Comment by K0nne** [comment] 2020-09-02 13:19
I think the error is thrown somewhere here:
https://github.com/Icinga/icinga-powershell-plugins/blob/master/plugins/Invoke-IcingaCheckDiskHealth.psm1#L182

**Comment by Yonas-net** [comment] 2020-09-02 13:38
First of all, before you do anything, you need to update the branch [like this,](https://github.com/Icinga/icinga-powershell-plugins/issues/55#issuecomment-685701802) because we might commit something afterwards and the changes will never reach you. What also irritates me is that the disk property ``Operational Status`` is not visible [here](https://github.com/Icinga/icinga-powershell-plugins/issues/53#issuecomment-685679149) in the Icinga plugin output, but if you run the checks manually like [here](https://github.com/Icinga/icinga-powershell-plugins/issues/53#issuecomment-681902609), you can see it.  And because this property does not exist, this error occurs in the Icinga plugin output.

 It seems that there is something wrong with the configuration that executes the check_by_pwsh remotely on the server and causes this disk property not to be recognized at all. But now I have added an additional check, which checks if this property exists at all and should the error not occur anymore. But if it is still there, please send me the configuration of check_by_pwsh.

**Comment by Yonas-net** [comment] 2020-09-03 13:38
Hiiii @aheinhold, The changes can be found in [this new branch](https://github.com/Icinga/icinga-powershell-plugins/tree/bugfix/throw-unhandled-error-calling-join-func-with-null-arg-53) and not [the previous ones](https://github.com/Icinga/icinga-powershell-plugins/tree/feature/implement-check-physicaldisk-35). So if you test something for DiskHealth from now on, check out [this branch](https://github.com/Icinga/icinga-powershell-plugins/tree/bugfix/throw-unhandled-error-calling-join-func-with-null-arg-53). Thanks 🙏

**Comment by aheinhold** [comment] 2020-09-10 12:38
Hi @Yonas-net 
i downloaded the ZIP-File from [this branch](https://github.com/Icinga/icinga-powershell-plugins/tree/bugfix/throw-unhandled-error-calling-join-func-with-null-arg-53) and transferred it to our test host.
I hope this is the right version!

The output at the servers commandline is ok, but the Icinga plugin-output is as follows:
```
[91mMethodInvocationException: [91mException calling "Join" with "2" argument(s): "Value cannot be null.
Parameter name: values"[0m
[OK] Check package "Physical Disk Package" (Match All)
\_ [OK] Check package "Disk #_Total" (Match All)
   \_ [OK] _Total avg. disk sec/read: 0s
   \_ [OK] _Total avg. disk sec/transfer: 0.002703s
   \_ [OK] _Total avg. disk sec/write: 0.002703s
   \_ [OK] _Total current disk queue length: 0
   \_ [OK] _Total disk read bytes/sec: 0B
   \_ [OK] _Total disk reads/sec: 0
   \_ [OK] _Total disk write bytes/sec: 149545.2B
   \_ [OK] _Total disk writes/sec: 5.13568
\_ [OK] Check package "Disk #0" (Match All)
   \_ [OK] C: avg. disk sec/read: 0s
   \_ [OK] C: avg. disk sec/transfer: 0.002703s
   \_ [OK] C: avg. disk sec/write: 0.002703s
   \_ [OK] C: current disk queue length: 0
   \_ [OK] C: disk read bytes/sec: 0B
   \_ [OK] C: disk reads/sec: 0
   \_ [OK] C: disk write bytes/sec: 149682.7B
   \_ [OK] C: disk writes/sec: 5.135689
   \_ [OK] C: Is Offline: False
   \_ [OK] C: Is ReadOnly: False
   \_ [OK] C: Status: OK
```

**Comment by LordHepipud** [comment] 2020-10-14 15:08
After further evaluation this was caused by missing permissions which is now resolved. The issue will be resolved with the PR

**Closed** 2020-10-28 14:39 UTC
Labels: bug
